### ISSUE TITLE
Core dump from Mmuer

### ISSUE THREAD

**Issue by wyim-pgl** [kakitone/finishingTool#1]
Dear Kakit,

Hello!

I have 375 Mbp draft and 7.5 corrected Pacbio reads.

When I try to run it generated core dump file.

$ file core.17720
core.17720: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/scratch/wgs/scaffold/finishingTool/MUMmer3.23/mummer -maxmatch -'

The log is below.

1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "abyss/self.ntref" of length 464633565
# construct suffix tree for sequence of length 464633565
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 4646335 characters per dot
#......................................................................................ERROR: mummer and/or mgaps returned non-zero
ERROR: Could not parse delta file, abyss/self.delta
error no: 400
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "abyss/greedy.ntref" of length 389013654
# construct suffix tree for sequence of length 389013654
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 3890136 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /scratch/wyim/iceplant/wgs/scaffold/finishingTool/MUMmer3.23/mummer abyss/greedy.ntref 216.69
# reading input file "/scratch/wyim/iceplant/wgs/scaffold/finishingTool/abyss/noEmbed_contigs_Double.fasta" of length 389013653
# matching query-file "/scratch/wyim/iceplant/wgs/scaffold/finishingTool/abyss/noEmbed_contigs_Double.fasta"
# against subject-file "abyss/greedy.ntref"

Please help to resolve it.

Won

**Comment by pb-jchin** [comment]
Discussed Mummer crash with Serge Koren, he mentioned if the fasta sequence line is too long, it might have problem. (I do have experience aligning Mbp with Mummer without any problem...)

**Comment by ascendo** [comment]
Yes I change my fasta file format width 60 and it generated error.

In Falcon remove_dup_ctg.py, it has no problem.

It might be my fasta format error.

**Comment by ascendo** [comment]
But I have no idea to figure it out.

**Comment by pb-jchin** [comment]
Maybe you can point the problematic fasta files to the Mummer project on Source Forge (http://mummer.sourceforge.net)  to see if anyone can help to take a look

**Comment by ascendo** [comment]
I will.

Thank you @pb-jchin

**Comment by kakitone** [comment]
I have added an option (namely -l True) for handling long fasta sequences in contigs.fasta. But I put it in experimental folder for now. You can take it out and put it in the working directory. 

Afterwards, you can then run 

        python finisherSC.py -l True destinedFolder MummerPath

@ascendo : Can you send me an email with a link to the files that you are working on so that I can use it as a test? And we can exchange some emails afterwards regarding the dataset that you are running. Thanks.
