### ISSUE TITLE
postnuc: Assertion `Len - Coord + 1 > 0' failed

### ISSUE THREAD

**Issue by thackl** [kakitone/finishingTool#10]
One of my runs failed with the following error message. Do know what is causing it and/or how to fix it?

```
# COMPLETETIME /home/thackl/software/MUMmer3.23/mummer finishersc-2.0/outGapFillRefine08.ntref 19.86
# SPACE /home/thackl/software/MUMmer3.23/mummer finishersc-2.0/outGapFillRefine08.ntref 18.10
4: FINISHING DATA
postnuc: postnuc.cc:1417: long int revC(long int, long int): Assertion `Len - Coord + 1 > 0' failed.
sh: line 1:  7991 Aborted                 /home/thackl/software/MUMmer3.23/aux_bin/postnuc -b 200 /nfs/bmm/crov/cr/assembly-refine/CrEa-gen-dp-4/finisher\
sc-2.0/smaller_improvedContig.fasta /nfs/bmm/crov/cr/assembly-refine/CrEa-gen-dp-4/relatedReads_Double.part-02.fasta finishersc-2.0/outGapFillRefine02 < \
finishersc-2.0/outGapFillRefine02.mgaps
ERROR: postnuc returned non-zero
ERROR: Could not parse input from 'Query File'.
Please check the filename and format, or file a bug report
ERROR: postnuc returned non-zero
```

**Comment by kakitone** [comment]
Hi, @thackl 

Thanks for reaching out ! 

This is an error message outputted by MUMmer's nucmer. Are you running multiple runs at the same time by initiating finisherSC from the same working directory? If so, a workaround is to initiate finisherSC from each of your data directories or initiate finisherSC one run at a time. 

Please let me know how things go. 

Thanks. 
Best Regards
Ka Kit

**Comment by thackl** [comment]
I've been running two finisherSC runs in parallel, but with different `folderName`, if this is what you refer to as working directory. Nevertheless, I did two more runs and so far could not reproduce the error... Maybe I mixed something up and was in fact running to runs in the same directory. I will let you know if the issue reappears...

**Comment by kakitone** [comment]
I mean the directory that you are in when you initiate the command. You may get into the data directory first and initiate command from there if you want to have multiple runs in parallel.
