### ISSUE TITLE
Retrieve sequences' headers and the joining information

### ISSUE THREAD

**Issue by uceleste** [kakitone/finishingTool#14]
Hi All,

FinisherSC succesfully ran on my assembly and it worked very well.

Now I am wondering if there is a way to know how the the sequences were joined into the new ones by recovering their headers.

For example:
I know that the sequence >Segkk0 of the improved3.fasta output includes the >Seq1 and >Seq2 of the original assembly.

Is it possible to obtain this kind of information?

Thanks

**Comment by kakitone** [comment]
e)Mapping between old contigs and new contigs [-o referenceName_QueryName ](e.g. you want to know how the contigs from contigs.fasta are mapped to improved3.fasta )

python finisherSC.py -o contigs.fasta_improved3.fasta destinedFolder mummerPath

**Comment by uceleste** [comment]
Thank you so much.
