### ISSUE TITLE
How to start: Installation procedure

### ISSUE THREAD

**Issue by Caro-Ca** [kakitone/finishingTool#20]
Hi!
I already dowloaded FinisherSC and ran it with this code: 
`python finisherSC.py -par 20 R18 MUMmer3.23/` 
and I have got this: 
```
  File "finisherSC.py", line 14
    print "Go Bears! ! !" 
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Go Bears! ! !")?
```
I can change it, but I am not sure if I am downloading the upgraded FinisherSC file. 

Thanks in advance.

**Comment by kakitone** [comment]
It looks like you are using Python 3 instead of Python 2.7.

You can try 

    python2 finisherSC.py -par 20 R18 MUMmer3.23/

To get the version at head, you can use the command 
    
    git clone https://github.com/kakitone/finishingTool.git

You are also encouraged to download MUMmer from its author to stay updated with their software. 
FYI, their website is http://mummer.sourceforge.net/ . After that, you need to adjust the path of MUMmer

    python2 finisherSC.py -par 20 R18 updatedmummerpath/

**Comment by Caro-Ca** [comment]
Thank you! By using python2 worked. On the other hand, I decided to start again downloading finisherSC and mummer. THese are my codes: 
```
git clone https://github.com/kakitone/finishingTool.git 

git clone https://github.com/mummer4/mummer 

python2 finisherSC.py -par 20 R18 mummer 
``` 
THis is what I've got at the end: 
```
sh: 1: mummer/nucmer: not found
sh: 1: mummer/show-coords: not found
fileoutname: len(extraList) noEmbed.fasta 0 40
nProc 20
1
sh: 1: mummer/nucmer: not found
sh: 1: mummer/show-coords: not found
fileoutname: len(extraList) improved.fasta 0 40
nProc 20
1
sh: 1: mummer/nucmer: not found
sh: 1: mummer/show-coords: not found
fileoutname: len(extraList) improved2.fasta 0 40
nProc 20
1
sh: 1: mummer/nucmer: not found
sh: 1: mummer/show-coords: not found
fileoutname: len(extraList) improved3.fasta 0 40
<3 Do cool things that matter <3
Time 361.065860033 
  
```
And comparing all the parameters (e.g. the NumContigs, Longest contig and N50) I've got the same results as without doing FinisherSC. For this reason, could you tell me what I am doing wrong. 

THanks for your answer.

**Comment by kakitone** [comment]
It looks like MUMmer is not installed properly. Please follow the installation instruction below by downloading the tar file, compiling the code and then installing MUMmer.

https://github.com/mummer4/mummer/blob/master/INSTALL.md

**Comment by Caro-Ca** [comment]
HI, 
I am new here. I downloaded the tar file : 
`wget https://github.com/mummer4/mummer/releases/download/v4.0.0beta2/mummer-4.0.0beta2.tar.gz
`
I unzipped it and then I am trying to use the codes provided as on the website. 
```
edgar@pathos:~/software/finishingTool/mummer$ configure --prefix=/mummer/INSTALL.md
configure: command not found
edgar@pathos:~/software/finishingTool/mummer$ ./configure --prefix=/mummer/INSTALL.md
-bash: ./configure: No such file or directory
```
THanks for your help!

**Comment by kakitone** [comment]
You may want to use the MUMmer in this git repository to get started then. It likely works out of the box. 

    python2 finisherSC.py -par 20 R18 MUMmer3.23/

**Comment by kakitone** [comment]
Alternatively, you can follow the commands here.  https://github.com/kakitone/finishingTool/blob/master/.travis.yml

  - wget http://sourceforge.net/projects/mummer/files/mummer/3.23/MUMmer3.23.tar.gz/download -O /tmp/mummer.tar.gz
  - tar -zxvf /tmp/mummer.tar.gz -C /tmp/
  - make install -C /tmp/MUMmer3.23/
  - wget https://www.dropbox.com/sh/zwws7lpvd322z45/AAD1voFVM0Subwm68R05Z7M5a?dl=1 -O /tmp/EcoliTestRun.zip
  - mkdir /tmp/EcoliTestRun
  - unzip /tmp/EcoliTestRun.zip contigs.fasta reference.fasta raw_reads.fasta -d /tmp/EcoliTestRun


You can then test your installation of FinisherSC and MUMmer inside the finishingTool directory by the following command
    
    python2 onlineTest.py

**Comment by Velastegui** [comment]
Thank you for your help. 
On the other hand, I already did the previous steps and I've got these: 
Init : Copying files : 
Integration test on FinisherSC:  
Integration test on FinisherSC:  /tmp/EcoliTestRun/
  File "finisherSC.py", line 14
    print "Go Bears! ! !" 
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Go Bears! ! !")?
ETeardown : Removing used files 
Init : Copying files : 
Integration test on FinisherSC:  
Teardown : Removing used files 
.Init : Copying files : 
Integration test on FinisherSC:  
Teardown : Removing used files 
.
======================================================================
ERROR: testFinisherSCEcoliTest (__main__.IsOddTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onlineTest.py", line 30, in testFinisherSCEcoliTest
    self.runningTestSet("/tmp/EcoliTestRun/" , 7)
  File "onlineTest.py", line 43, in runningTestSet
    lenDic = IORobot.obtainLength(self.testingFolder, "/improved3.fasta")
  File "/home/edgar/software/finishingTool/IORobot.py", line 11, in obtainLength
    f = open(folderName + fileName, 'r')
IOError: [Errno 2] No such file or directory: 'unitTestFolder/improved3.fasta'

----------------------------------------------------------------------
Ran 3 tests in 2.069s

FAILED (errors=1)

**Comment by Caro-Ca** [comment]
Thank you for your help!
On the other hand, I've done the previous steps and I've got these:
```
Init : Copying files : 
Integration test on FinisherSC:  
Integration test on FinisherSC:  /tmp/EcoliTestRun/
  File "finisherSC.py", line 14
    print "Go Bears! ! !" 
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Go Bears! ! !")?
ETeardown : Removing used files 
Init : Copying files : 
Integration test on FinisherSC:  
Teardown : Removing used files 
.Init : Copying files : 
Integration test on FinisherSC:  
Teardown : Removing used files 
.
======================================================================
ERROR: testFinisherSCEcoliTest (__main__.IsOddTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onlineTest.py", line 30, in testFinisherSCEcoliTest
    self.runningTestSet("/tmp/EcoliTestRun/" , 7)
  File "onlineTest.py", line 43, in runningTestSet
    lenDic = IORobot.obtainLength(self.testingFolder, "/improved3.fasta")
  File "/home/edgar/software/finishingTool/IORobot.py", line 11, in obtainLength
    f = open(folderName + fileName, 'r')
IOError: [Errno 2] No such file or directory: 'unitTestFolder/improved3.fasta'

----------------------------------------------------------------------
Ran 3 tests in 2.069s

FAILED (errors=1)
```

**Comment by kakitone** [comment]
Ah yes, you need to use python2 in this line too

https://github.com/kakitone/finishingTool/blob/a1f2608a9090adde1108451d2efb034461a75ad5/onlineTest.py#L42

Change         

    os.system("python finisherSC.py -par 4 "+ self.testingFolder + " "+ self.mummerPath)

to 
     
    os.system("python2 finisherSC.py -par 4 "+ self.testingFolder + " "+ self.mummerPath)

**Comment by Caro-Ca** [comment]
After doing what you previously told me, I tested python2 onlineTest.py and I've got this:
```
...............
# CONSTRUCTIONTIME /tmp/MUMmer3.23/mummer unitTestFolder/improved3.fastafillmiss.ntref 2.51
# reading input file "/home/edgar/software/finishingTool/unitTestFolder/improved3tmp.fasta" of length 4660697
# matching query-file "/home/edgar/software/finishingTool/unitTestFolder/improved3tmp.fasta"
# against subject-file "unitTestFolder/improved3.fastafillmiss.ntref"
# COMPLETETIME /tmp/MUMmer3.23/mummer unitTestFolder/improved3.fastafillmiss.ntref 7.86
# SPACE /tmp/MUMmer3.23/mummer unitTestFolder/improved3.fastafillmiss.ntref 8.99
4: FINISHING DATA
fileoutname: len(extraList) improved3.fasta 0 7
<3 Do cool things that matter <3
Time 546.203663111
{'Segkk1': 1525403, 'Segkk0': 379038, 'Segkk3': 2044060, 'Segkk2': 15323, 'Segkk5': 181350, 'Segkk4': 261279, 'Segkk6': 254238}
Teardown : Removing used files 
.Init : Copying files : 
Integration test on FinisherSC:  
Teardown : Removing used files 
.Init : Copying files : 
Integration test on FinisherSC:  
Teardown : Removing used files 
.
----------------------------------------------------------------------
Ran 3 tests in 548.319s

OK
```
Afterwards, I ran: 

`python2 finisherSC.py -par 20 R18 MUMmer3.23/ `

getting different errors: 

```
ERROR: The following critical files could not be used
/Users/kakitlam/Downloads/MUMmer3.23/aux_bin/postnuc
/Users/kakitlam/Downloads/MUMmer3.23/aux_bin/prenuc
/Users/kakitlam/Downloads/MUMmer3.23/mgaps
/Users/kakitlam/Downloads/MUMmer3.23/mummer
Check your paths and file permissions and try again
MUMmer3.23/show-coords: 1: MUMmer3.23/show-coords: Syntax error: Unterminated quoted string
fileoutname: len(extraList) improved3.fasta 0 40
<3 Do cool things that matter <3
Time 460.321681976

```

**Comment by kakitone** [comment]
Great. From the output of onlineTest.py, you have just successfully used FinisherSC on an Ecoli genome , which is stored in /tmp/EcoliTestRun ! 

Your MUMmer was installed in /tmp/MUMmer3.23/

Therefore, try this, 

    python2 finisherSC.py -par 20 R18 /tmp/MUMmer3.23/


But in the future, you want to follow the previous  comment https://github.com/kakitone/finishingTool/issues/20#issuecomment-509663865 

but install MUMmer in a permanent directory(e.g. your home directory) other than /tmp/MUMmer3.23/

**Comment by Caro-Ca** [comment]
Thank you very much for your help! You were very useful.
