### ISSUE TITLE
Why nothing changed in my contigs.fasta and improved3.fasta? 

### ISSUE THREAD

**Issue by lillianleung** [kakitone/finishingTool#21]

**Comment by lillianleung** [comment]
I used finisherSC with no error, but get the same output between contigs.fasta and improved3.fasta, I do not know whether can improve or i make other mistakes. Thanks!
this is my command (with my raw_reads.fasta and contigs.fasta in the path: python finisherSC.py -par 16 03.polish/finisher_wtdbg2 /share/app/MUMmer-3.23

**Comment by kakitone** [comment]
If you obtain improved3.fasta, then FinisherSC has already finished its operations. Your command looks good to me and so I think you did not make any mistakes in using FinisherSC.

**Comment by wuxiaopei0509** [comment]
I got the same problem ,nothing changed in the improved3.fasta.what's he issue?
