### ISSUE TITLE
KeyError: '000000F'

### ISSUE THREAD

**Issue by lennythomas** [kakitone/finishingTool#3]
Getting the following error when running finisherSC.py

```
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "/Volumes/HD/lt/Desktop/assembly/self.ntref" of length 1326462
# construct suffix tree for sequence of length 1326462
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 13264 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /usr/src/app/finishingTool/MUMmer3.23/mummer /Volumes/HD/lt/Desktop/assembly/self.ntref 0.33
# reading input file "/Volumes/HD/lt/Desktop/assembly/contigs.fasta" of length 1326461
# matching query-file "/Volumes/HD/lt/Desktop/assembly/contigs.fasta"
# against subject-file "/Volumes/HD/lt/Desktop/assembly/self.ntref"
# COMPLETETIME /usr/src/app/finishingTool/MUMmer3.23/mummer /Volumes/HD/lt/Desktop/assembly/self.ntref 1.02
# SPACE /usr/src/app/finishingTool/MUMmer3.23/mummer /Volumes/HD/lt/Desktop/assembly/self.ntref 2.55
4: FINISHING DATA
Traceback (most recent call last):
  File "finishingTool/finisherSC.py", line 76, in <module>
    mainFlow(newFolderName, newMummerLink, args['pickup'], args['mapcontigs'])
  File "finishingTool/finisherSC.py", line 19, in mainFlow
    nonRedundantResolver.removeEmbedded(folderName , mummerLink)
  File "/usr/src/app/finishingTool/nonRedundantResolver.py", line 31, in removeEmbedded
    l1, l2 = lenDic[name1], lenDic[name2]
KeyError: '000000F'
```

I installed from GitHub and ran `make clean` and `make all`. `make check` says all is ok. Any thoughts?

**Comment by kakitone** [comment]
Would you mind trying to run the test set provided in the sandbox example first?
As for the key error, is "000000F" a contig name? Also, can you run 'sed' in command line properly, it is needed for finisherSC to run properly.   But you can shoot me an email with the files that you are working on and I can take a closer look.

**Comment by lennythomas** [comment]
The example dataset runs fine. Yes, 000000F is a config name that produced from running FALCON.
`>000000F 000000380:E~000000043:B~000004270:E~000004270:E ctg_linear 220339 750832` is the full config name. I checked sed and it is version 4.2.2 and seems to run ok.

**Comment by lennythomas** [comment]
The weird thing is if I just modify that first FASTA header to `>000000F`, but leave all the rest in the same format it completes just fine.

**Comment by kakitone** [comment]
I see. It actually depends on how MUMmer handle header's name as well. If you don't mind, how about changing the contig name to be something like Seg1, Seg2, ...etc ?

**Comment by lennythomas** [comment]
I can patch the file. Thanks.

**Comment by kakitone** [comment]
Hey, @lennythomas,  you may also want to try this to do the name patching  
    
        perl -pe 's/>[^\$]*$/">Seg" . ++$n ."\n"/ge' oldFileName > newFileName

**Comment by damioresegun** [comment]
Hi, I've been having this same issue the past few days. I have tried everything suggested above and I am still having the same issue. Any suggestions?

**Comment by Johnsonzcode** [comment]
Same, after name patching, still got same error.
