### ISSUE TITLE
no parallelism for the first step?

### ISSUE THREAD

**Issue by Imoteph** [kakitone/finishingTool#4]
Hi,

I have problem that the pipeline is too slow. I used following command:

args {'mapcontigs': None, 'mummerLink': '/home/XXX/bin/', 'fast': 'True', 'folderName': 'finisherSC_fast_mode/', 'large': None, 'pickup': None, 'parallel': '30'}

It runs already 5 days but it only were able to generate 113 fasta entries in self.mgaps of 3000. 

Currently only one mgaps is running. So what I'm doing wrong?

**Comment by Imoteph** [comment]
Ok after digging more to the code, I realized that maybe using -l True could be the solution to my problem. But why is the number of small files later on hard coded?

**Comment by kakitone** [comment]
My experience is that if you break it down into too many small files, the running time may be worse beyond certain point. So, the default is hardcoded to prevent users from thinking that increasing the number of small files will always decrease the running time. Anyway, let me know if you can run through finally.

**Comment by Imoteph** [comment]
Yes, I will. Currently it is running (still running phase 1 ).

**Comment by Imoteph** [comment]
So It finished ;). After a month with a plant genome. But first of all great tool!  I have some ideas for improvements. Please get in contact with me, so I can tell you what I found or where I see improvements.
