### ISSUE TITLE
mummerplot can't work

### ISSUE THREAD

**Issue by pyhuang1** [kakitone/finishingTool#5]
when I type the following at the command line
$ mummerplot -p out out.delta

it shows error message as follows, would you please show me how to solve this problem, thank you!
defined(%hash) is deprecated at /usr/bin/mummerplot line 884.
	(Maybe you should just omit the defined()?)
defined(%hash) is deprecated at /usr/bin/mummerplot line 894.
	(Maybe you should just omit the defined()?)
defined(%hash) is deprecated at /usr/bin/mummerplot line 981.
	(Maybe you should just omit the defined()?)
defined(%hash) is deprecated at /usr/bin/mummerplot line 991.
	(Maybe you should just omit the defined()?)
defined(%hash) is deprecated at /usr/bin/mummerplot line 1034.
	(Maybe you should just omit the defined()?)
defined(%hash) is deprecated at /usr/bin/mummerplot line 1044.
	(Maybe you should just omit the defined()?)
gnuplot 4.6 patchlevel 4
Reading delta file out.delta
Writing plot files out.fplot, out.rplot
Writing gnuplot script out.gp
Forking mouse listener
Rendering plot to screen
unrecognized option -geometry
Cannot open load file '500x500+0+0'
"500x500+0+0", line 0: util.c: No such file or directory

WARNING: Unable to run 'gnuplot -geometry 500x500+0+0 -title mummerplot out.gp', Inappropriate ioctl for device

**Comment by kakitone** [comment]
How about writing the image to file ?

        mummerplot --png  out.delta

**Comment by pyhuang1** [comment]
Thank you! It works.

Best,
Pei-Ying Huang

2015-05-27 12:17 GMT+08:00 kakitone <notifications@github.com>:
