### ISSUE TITLE
RuntimeError('cannot join current thread',)

### ISSUE THREAD

**Issue by thackl** [kakitone/finishingTool#9]
I ran into the following error after the mummer in "removeEmbedded" step:
`Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored`

However, finisherSC seems to continue fine. I just wanted to know if this is a critical error or if I can just ignore it.

Cheers

**Comment by kakitone** [comment]
Hi, @thackl ,

Thanks for the question ! Are you using -f True -l True options? I am suspecting that is an issue related to  parallelization. 

Indeed, if finisherSC continue running, then it should be fine, only that there may be some zombie process around. 

But, I do have a version that is going to fix these zombie processes. If you are interested, I can let you know when I push that version. 

Cheers
Ka Kit

**Comment by thackl** [comment]
I've run 4 runs, each with `-par 20`, and each produced the error 5 times and also already after the initial mummer run during removeEmbedded (which as far as I understand, is not parallelized ?). One run was with `-f True`. I did not used `-l` - the data set is 30 Mb in 230 contigs. I can provide you with the logs if that would help you in any way...

Apart from that the runs seem fine, I end up with contig number reduced to >160 and a slightly increased assembly size.

I didn't notice any zombies hanging around, so no need to notify me. Also I will check your repository from time to time and download new releases anyway.

Cheers

**Comment by kakitone** [comment]
Sounds good.
